//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingProcess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educationinfo
    {
        public int Educationid { get; set; }
        public int EmployeeId { get; set; }
        public string SSC_School_Name { get; set; }
        public Nullable<int> SSC_percentage { get; set; }
        public Nullable<int> SSC_Passing_Year { get; set; }
        public string HSC_College_Name { get; set; }
        public Nullable<int> HSC_percentage { get; set; }
        public Nullable<int> HSC_Passing_Year { get; set; }
        public string Degree_College_Name { get; set; }
        public string Degree { get; set; }
        public int Degree_percentage { get; set; }
        public Nullable<int> Degree_Passing_Year { get; set; }
        public string University { get; set; }
        public string Highest_Qualificaion { get; set; }
    
        public virtual Personalinfo Personalinfo { get; set; }
    }
}
