//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingProcess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnboardingEntities1 : DbContext
    {
        public OnboardingEntities1()
            : base("name=OnboardingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Educationinfo> Educationinfoes { get; set; }
        public virtual DbSet<Personalinfo> Personalinfoes { get; set; }
        public virtual DbSet<Professionalinfo> Professionalinfoes { get; set; }

    }
}
