//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingProcess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personalinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personalinfo()
        {
            this.Educationinfoes = new HashSet<Educationinfo>();
            this.Professionalinfoes = new HashSet<Professionalinfo>();
        }
    
        public int EmployeeId { get; set; }
        public string Fullname { get; set; }
        public string Gender { get; set; }
        public string Locality_Address { get; set; }
        public string State_N { get; set; }
        public string City { get; set; }
        public int Contactno { get; set; }
        public string Emailid { get; set; }
        public string Passportfilepath { get; set; }
        public string Signaturefilepath { get; set; }
        public string Adharcardfilepath { get; set; }
        public string SSCfilepath { get; set; }
        public string HSCfilepath { get; set; }
        public string Degreefilepath { get; set; }
        public string Resumefilepath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Educationinfo> Educationinfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professionalinfo> Professionalinfoes { get; set; }
    }
}
